### ISSUE TITLE
can't use in nuxt using import

### ISSUE THREAD

**Issue by Djeisen642** [BelkaLab/material-color-hash#2]
had to use

> const toMaterialStyle = require('material-color-hash')
> toMaterialStyle.default(word)

**Comment by Djeisen642** [comment]
using workaround in https://github.com/Djeisen642/htm-project
email is "whatever" right now and password is "whatever"

**Comment by GiovanniFrigo** [comment]
I've just committed an attempt fix for this issue in version **0.1.3**, could you please try to update your dependency and see if this time the `import` syntax works?

**Comment by Djeisen642** [comment]
That worked for me. Interesting fix. Thanks!

**Comment by GiovanniFrigo** [comment]
Nice! glad that solved the issue ;)
